export const CART_ADD_DISH = "CART_ADD_DISH";
export const CART_REMOVE_DISH = "CART_REMOVE_DISH";
export const CART_SAVE_SHIPPING = "CART_SAVE_SHIPPING";
export const CART_SAVE_PAYMENT = "CART_SAVE_PAYMENT";